<?php
class MvcModule extends Process{
	
	/*
	Enable URL segments for the template,

	use it as follow /template_name/action/, in this case $input->urlSegments[1] = action.

	create class on template file, set controller to that class like
	$mvc->set_controller($controler_name);
	and set an action as follow:

	$mvc->set_action($input->urlSegments[1]);

	*/
	public $template = null;
	public $controller = null;
	public $view = null;
	public $action = null;
	public $layout = null;
	//Page values
	public $header = null;
	public $title = null;
	public $body = null;
	public $snippets = null;//should be an array format

	public static function getModuleInfo(){
		return array(
			'title' => 'MVC',
			'summary' => __('Module that enables MVC like programming'),
			);
	}

	public function init(){
		$this->setFuel("mvc", $this);
	}

	public function set_template($template = null){
		if($template != null){
			$this->template = $template;
		}
	}

	public function set_controller($controller = null){
		if($controller != null){
			$this->controller = $controller;
		}
	}

	public function set_action($action = null){
		if($action != null){
			$this->action = $action;
		}
	}

	public function get_title(){
		return $this->controller->title;
	}

	public function get_custom_snippets(){
		return $this->controller->snippets;
	}

	public function get_headers(){
		$header_html = "";
		foreach($this->controller->javascript as $js_src){
			$header_html .= '<script type="text/javascript" src="' . $this->config->urls->templates . 'assets/scripts/' . $js_src . '"></script>' . PHP_EOL;
		}
		foreach($this->controller->styles as $style_src){
			$header_html .= '<link href="' . $this->config->urls->templates . 'assets/styles/' . $style_src . '" rel="stylesheet" type="text/css">'. PHP_EOL;
		}
		return $header_html;
	}

	public function render(){
		if(isset($this->action)){
			$this->title = $this->get_title();
			$this->header= $this->get_headers();
			$this->snippets = $this->get_custom_snippets();
			//an action is set
			if(method_exists($this->controller, $this->action)){
				$this->body = $this->controller->{$this->action}();
			}elseif (isset($this->controller->index_action)) {
				$this->body = $this->controller->index_action;
			}
			$this->layout = $this->controller->layout;
			echo $this->render_layout();
		}else{
			return 'Error';
		}
	}

	public function render_layout(){
		$title = $this->title;
		$body = $this->body;
		$header = $this->header;
		if (is_array($this->snippets) && !empty($this->snippets)) {
	        foreach($this->snippets as $key => $snippet){
	        	ob_start();
	        	include('snippets/' . $snippet);
	        	${$key} = ob_get_clean();
	        }
	    }
		ob_start();
	    include('layouts/' . $this->layout);
	    return ob_get_clean();
	}
}