<?php
class MvcModule extends Process{
	
	/*
	Enable URL segments for the template,

	use it as follow /template_name/action/, in this case $input->urlSegments[1] = action.

	create class on template file, set controller to that class like
	$mvc->set_controller($controler_name);
	and set an action as follow:

	$mvc->set_action($input->urlSegments[1]);

	*/
	public $template = null;
	public $controller = null;
	public $view = null;
	public $action = null;

	public static function getModuleInfo(){
		return array(
			'title' => 'MVC',
			'summary' => __('Module that enables MVC like programming'),
			);
	}

	public function init(){
		$this->setFuel("mvc", $this);
	}

	public function set_template($template = null){
		if($template != null){
			$this->template = $template;
		}
	}

	public function set_controller($controller = null){
		if($controller != null){
			$this->controller = $controller;
		}
	}

	public function set_action($action = null){
		if($action != null){
			$this->action = $action;
		}
	}

	public function render(){
		if(isset($this->action)){
			//an action is set
			if(method_exists($this->controller, $this->action)){
				return $this->controller->{$this->action}();
			}elseif (isset($this->controller->index_action)) {
				return $this->controller->index_action;
			}else{
				if(method_exists($this->controller, 'index')){
					return $this->controller->index;
				}
			}
		}else{
			return 'Error';
		}
	}
}